[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skyrl-gym"
version = "0.1.1"
description = "RL environments for LLMs implemented with the Gymnasium API."
authors = [
    { name = "NovaSkyAI AI Team"}
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "func_timeout",
    "pandas", 
    "requests",
    "omegaconf",
    "reasoning-gym==0.1.25",
]

[project.urls]
Repository = "https://github.com/NovaSky-AI/SkyRL"

[tool.setuptools.packages.find]
include = ["skyrl_gym*"]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "F722"
]
