"""Trainer-facing import surface for the canonical pre-launch environment manager."""

from marinskyrl.environment_contract import (
    DEBUG_ARTIFACT_DIR_ENV as DEBUG_ARTIFACT_DIR_ENV,
    DEBUG_MODE_ENV as DEBUG_MODE_ENV,
    COLLECTIVE_PHASE_DIAGNOSTICS_ENV as COLLECTIVE_PHASE_DIAGNOSTICS_ENV,
    DEFAULT_NCCL_TRACE_BUFFER_SIZE as DEFAULT_NCCL_TRACE_BUFFER_SIZE,
    DEFAULT_RUNAI_STREAMER_LOG_TO_STDERR as DEFAULT_RUNAI_STREAMER_LOG_TO_STDERR,
    DEFAULT_RUNAI_STREAMER_S3_REQUEST_TIMEOUT_MS as DEFAULT_RUNAI_STREAMER_S3_REQUEST_TIMEOUT_MS,
    ENV_VAR_SPECS as ENV_VAR_SPECS,
    FR_DUMP_TEMP_FILE_ENV as FR_DUMP_TEMP_FILE_ENV,
    HF_HUB_OFFLINE_ENV as HF_HUB_OFFLINE_ENV,
    NCCL_DEBUG_INFO_TEMP_FILE_ENV as NCCL_DEBUG_INFO_TEMP_FILE_ENV,
    NUMA_AFFINITY_ENV as NUMA_AFFINITY_ENV,
    PYTHONFAULTHANDLER_ENV as PYTHONFAULTHANDLER_ENV,
    RAY_USE_UVLOOP_ENV as RAY_USE_UVLOOP_ENV,
    RUNAI_STREAMER_LOG_TO_STDERR_ENV as RUNAI_STREAMER_LOG_TO_STDERR_ENV,
    RUNAI_STREAMER_S3_REQUEST_TIMEOUT_MS_ENV as RUNAI_STREAMER_S3_REQUEST_TIMEOUT_MS_ENV,
    UV_USE_IO_URING_ENV as UV_USE_IO_URING_ENV,
    VLLM_BATCH_INVARIANT_ENV as VLLM_BATCH_INVARIANT_ENV,
    VLLM_USE_V2_MODEL_RUNNER_ENV as VLLM_USE_V2_MODEL_RUNNER_ENV,
    DebugMode as DebugMode,
    EnvVarManager as EnvVarManager,
    EnvVarScope as EnvVarScope,
    EnvVarSource as EnvVarSource,
    ensure_debug_artifact_directories as ensure_debug_artifact_directories,
    managed_environment_names as managed_environment_names,
    nccl_diagnostics_environment as nccl_diagnostics_environment,
    write_process_manifest as write_process_manifest,
)
