"""The rollout-buffer training loop.

Rollout workers generate continuously into the ``TrainingContext``'s buffer while the trainer reads one
selected batch per step, trains on it, syncs weights to inference, and publishes the new policy step.
``global_step`` is the step being trained: its batch was generated by policies at most
``max_staleness_steps`` steps older, and ``global_step - 1`` optimizer steps have completed before it.
"""

import asyncio
from typing import List, Literal

from loguru import logger

from marinskyrl.runtime_options import WeightSyncTransport
from skyrl_train.distillation import DISTILLATION_SCORED_TOKENS_METRIC
from skyrl_train.distillation_adapters import AsyncRoutedTeacherScoreTicket, RoutedScoredDistillationBatch
from skyrl_train.distillation_runtime import AsyncDistillationRuntime
from skyrl_train.group_admission import AdmissionProgressWatchdog
from skyrl_train.rollouts.buffer import RolloutGroup
from skyrl_train.rollouts.context import TrainingContext, TrainingContextState
from skyrl_train.telemetry import critical_phase, record_policy_step, record_rollout_staleness
from skyrl_train.timing_observability import publish_step_timings
from skyrl_train.trainer import RayPPOTrainer
from skyrl_train.training_batch import TrainingInputBatch
from skyrl_train.trajectory_runners.base import TrajectoryBatch
from skyrl_train.trajectory_runners.trajectory_processing import concatenate_trajectory_batches
from skyrl_train.utils import Timer, get_system_memory_metrics
from skyrl_train.utils.algorithm_registry import policy_loss_requires_rollout_logprobs
from skyrl_train.utils.logging_utils import log_exception_as_text
from skyrl_train.utils.progress import tqdm
from skyrl_train.utils.trainer_utils import ResumeMode
from skyrl_train.weight_sync.expert_block.driver import ExpertBlockSync


class FullyAsyncRayPPOTrainer(RayPPOTrainer):
    # Set at startup when generator.weight_sync_transport is expert_block.
    _expert_block_sync: ExpertBlockSync | None = None

    def __init__(self, *, context: TrainingContext, **kwargs):
        cfg = kwargs["cfg"]
        # The base initializer reads these through `_configure_training_schedule`.
        self.context = context
        self.mini_batch_size = cfg.trainer.policy_mini_batch_size
        super().__init__(**kwargs)
        if self.cfg.trainer.train_batch_size != self.mini_batch_size:
            raise ValueError("train_batch_size must equal policy_mini_batch_size for fully async training")
        if self.cfg.generator.batched:
            raise ValueError("batched generation is not supported for fully async training")
        if not self.cfg.generator.async_engine:
            raise ValueError("async_engine must be true for fully async training")
        if self.colocate_all:
            raise ValueError("colocate_all is not supported for fully async training yet")
        self.group_admission_stall_timeout = self.cfg.trainer.algorithm.group_admission.stall_timeout
        self._restored_rollout_state: TrainingContextState | None = None
        self._async_distillation_runtime: AsyncDistillationRuntime | None = None
        self._async_distillation_tickets: dict[str, AsyncRoutedTeacherScoreTicket] = {}

    def configure_async_distillation(self, runtime: AsyncDistillationRuntime) -> None:
        """Install admitted-group teacher scoring before the training loop starts."""
        if self._async_distillation_runtime is not None:
            raise RuntimeError("fully-async distillation runtime is already configured")
        if self._sync_distillation_runtime is not None:
            raise RuntimeError("cannot combine synchronous and fully-async distillation runtimes")
        self._async_distillation_runtime = runtime
        self._domain_balancer = runtime.domain_balancer

    def _configure_training_schedule(self):
        """Count steps in batches of prompt groups; the context's loader replaces the dataloader."""
        self.num_steps_per_epoch = len(self.train_dataset) // self.mini_batch_size
        if self.num_steps_per_epoch == 0:
            raise ValueError(
                f"the training dataset has {len(self.train_dataset)} prompts, fewer than one batch of "
                f"{self.mini_batch_size}"
            )
        self.total_training_steps = self.num_steps_per_epoch * self.cfg.trainer.epochs
        max_steps = self.cfg.trainer.get("max_steps")
        if max_steps is not None and max_steps > 0:
            self.total_training_steps = min(self.total_training_steps, max_steps)
        logger.info(f"Steps per epoch: {self.num_steps_per_epoch}, total training steps: {self.total_training_steps}")

    def _num_steps_per_epoch(self) -> int:
        return self.num_steps_per_epoch

    async def _rollout_state(self) -> TrainingContextState:
        return await self.context.state_dict()

    def _restore_rollout_state(self, state: object, trainer_state: dict) -> None:
        if not isinstance(state, TrainingContextState):
            raise ValueError(f"checkpoint data state is a {type(state).__name__}, not a rollout context state")
        self._restored_rollout_state = state

    async def shutdown(self) -> None:
        """Stop rollout dispatch before releasing trainer resources."""
        if self._shutdown_complete:
            return
        try:
            await self.context.close()
            await self._drain_checkpoint_upload()
        finally:
            if self._expert_block_sync is not None:
                try:
                    await self._expert_block_sync.close()
                except Exception:
                    logger.exception("Closing the expert-block weight sync failed during shutdown")
            if self._async_distillation_runtime is not None:
                await self._close_distillation_runtime(self._async_distillation_runtime)
            await super().shutdown()

    async def train(self):
        """Run the rollout-buffer training loop."""
        self.global_step = 0
        try:
            if self._async_distillation_runtime is not None:
                await self._async_distillation_runtime.start()
            await self._startup_trajectory_runner()
            await self._train_loop()
        except Exception as e:
            log_exception_as_text(f"Train loop failed at global_step {self.global_step}", e)
            raise
        finally:
            await self.shutdown()

    async def _train_loop(self):
        if self.resume_mode != ResumeMode.NONE:
            with Timer("load_checkpoints", self.all_startup_timings):
                self.global_step, _ = self.load_checkpoints()
                logger.info(f"Resumed training from global_step {self.global_step}")
                if self._restored_rollout_state is not None:
                    await self.context.load_state_dict(self._restored_rollout_state)
                    self._restored_rollout_state = None

        with Timer("init_weight_sync_state", self.all_startup_timings):
            if self.cfg.generator.weight_sync_transport == WeightSyncTransport.EXPERT_BLOCK:
                self._expert_block_sync = ExpertBlockSync(
                    policy_model=self.policy_model,
                    inference_engine_client=self.inference_engine_client,
                    timeout_seconds=self.cfg.generator.expert_block_sync.timeout_seconds,
                )
                for phase, seconds in (await self._expert_block_sync.prepare()).items():
                    self.all_startup_timings[f"expert_block_sync/{phase}"] = seconds
            else:
                self.init_weight_sync_state()

        with Timer("sync_weights_to_inference_engines", self.all_startup_timings) as weight_update_timer:
            await self._sync_policy_weights_and_offload_optimizer(sync_phase="initial")
        self._log_weight_update_completed(reason="initial", duration_seconds=weight_update_timer.duration)

        # The loaded global_step counts completed steps, so >= treats a resume exactly at max_steps as complete.
        if self.resume_mode != ResumeMode.NONE and self.global_step >= self.total_training_steps:
            await self._handle_resume_at_max_steps()
            return

        self._log_startup_timings()

        self._control.reset()
        self._control = await self.callback_handler.call_event_async(
            "on_train_begin",
            self._create_trainer_state(epoch=self.global_step // self.num_steps_per_epoch),
            self._control,
            trainer=self,
        )
        if self._control.should_evaluate and self.eval_dataset is not None:
            with Timer("eval", self.all_timings):
                eval_metrics = await self.eval()
                self._log_metrics_stdout(eval_metrics, step=self.global_step, kind="eval")
                self.tracker.log(eval_metrics, step=self.global_step, commit=self.cfg.trainer.tracker_commit_each_step)
            self._control.should_evaluate = False

        self.context.start()
        await self.context.publish(self.global_step + 1)

        pbar = tqdm(total=self.total_training_steps, initial=self.global_step, desc="Training Step Progress")
        last_completed_step = self.global_step
        while self.global_step < self.total_training_steps:
            self.global_step += 1
            epoch = (self.global_step - 1) // self.num_steps_per_epoch
            with Timer("step", self.all_timings) as step_timer:
                await self._train_step(epoch)
                step_state = self._create_trainer_state(epoch, active_step_duration=step_timer.elapsed)
                await self._run_step_end_callbacks(step_state)

            if self._control.should_log:
                log_payload = {
                    **self.all_metrics,
                    **{f"timing/{k}": v for k, v in self.all_timings.items()},
                    **get_system_memory_metrics(),
                }
                self._log_metrics_stdout(log_payload, step=self.global_step, kind="train")
                self.tracker.log(log_payload, step=self.global_step, commit=self.cfg.trainer.tracker_commit_each_step)
                await self.callback_handler.call_event_async(
                    "on_log", step_state, self._control, logs=log_payload, trainer=self
                )
            self._log_training_step_completed(epoch=epoch, duration_seconds=step_timer.duration)

            self.all_metrics = {}
            step_duration = self.all_timings.get("step")
            if step_duration is not None:
                self._step_time_history.append(step_duration)
            publish_step_timings(self.all_timings, self.global_step)
            self.all_timings = {}
            pbar.update(1)
            last_completed_step = self.global_step
            record_policy_step(self.global_step)

            if self.global_step % self.num_steps_per_epoch == 0:
                await self._end_epoch(epoch)
            if self._control.should_training_stop:
                logger.info("Training stopped early by callback")
                break
        pbar.close()

        await self._finalize_training(completed_step=last_completed_step, epoch=self.cfg.trainer.epochs - 1)
        logger.info("Training done!")

    async def _train_step(self, epoch: int) -> None:
        """Train on one batch, sync the new weights, and open leases for the next step."""
        logger.info("Rollout batch started: step={} required_groups={}", self.global_step, self.mini_batch_size)
        with (
            Timer("wait_for_generation_buffer", self.all_timings) as rollout_wait_timer,
            critical_phase("rollout_or_inference_wait", self.global_step),
        ):
            groups, selection_metrics = await self.context.next_batch(
                stall_timeout=self._rollout_stall_timeout(),
                on_admitted=self._submit_admitted_groups_for_teacher_scoring,
            )
        self.all_metrics.update(selection_metrics)

        scored_distillation = None
        if self._async_distillation_runtime is not None:
            with Timer("wait_for_teacher_evidence", self.all_timings):
                scored_distillation = await self._await_admitted_teacher_evidence(groups)

        training_input = await asyncio.to_thread(self.convert_rollout_groups_to_training_input, groups)
        if scored_distillation is not None:
            self.all_metrics.update(
                self._async_distillation_runtime.attach_to_training_input(training_input, scored_distillation)
            )
            self.all_metrics.update(
                {
                    "distillation/teacher_count": float(
                        len({route.teacher_id for scored in scored_distillation for route in scored.routes})
                    ),
                    DISTILLATION_SCORED_TOKENS_METRIC: float(
                        sum(scored.distillation.valid_mask.sum().item() for scored in scored_distillation)
                    ),
                }
            )
        response_ids = [response for group in groups for response in group.trajectory_batch["response_ids"]]
        logger.info(
            "Rollout batch completed: step={} groups={} trajectories={} response_tokens={} staleness_mean={:.3f} "
            "staleness_max={} duration_seconds={:.3f}",
            self.global_step,
            len(groups),
            len(response_ids),
            sum(len(response) for response in response_ids),
            self.all_metrics["async/staleness_mean"],
            self.all_metrics["async/staleness_max"],
            rollout_wait_timer.duration,
        )

        # Records whether this batch lacked rollout logprobs, so TIS fell back to the standard policy loss.
        # A skipped fraction near 1.0 means rollout-logprob capture is broken.
        if self.cfg.trainer.algorithm.use_tis:
            batch_skipped = float(getattr(self, "_tis_batch_skipped_no_logprobs", 0.0))
            self._tis_skipped_count = getattr(self, "_tis_skipped_count", 0.0) + batch_skipped
            self._tis_total_count = getattr(self, "_tis_total_count", 0.0) + 1.0
            self.all_metrics.update(
                {
                    "tis/batch_skipped_no_logprobs": batch_skipped,
                    "tis/skipped_fraction": self._tis_skipped_count / self._tis_total_count,
                }
            )

        with Timer("run_training", self.all_timings):
            status = await self._run_training(training_input)
        self._log_optimizer_step_completed(
            epoch=epoch,
            training_input=training_input,
            duration_seconds=self.all_timings["train_critic_and_policy"],
        )

        # The engines are shared by every rollout worker. Pausing them aborts in-flight requests, which
        # resume on the new weights; the buffer measures the staleness that results.
        with Timer("sync_weights", self.all_timings) as weight_update_timer:
            await self._sync_policy_weights_and_offload_optimizer(sync_phase="training_step")
        self._log_weight_update_completed(reason="training_step", duration_seconds=weight_update_timer.duration)
        if self.global_step < self.total_training_steps:
            await self.context.publish(self.global_step + 1)

        logger.info(status)
        self.all_metrics.update({"trainer/epoch": epoch, "trainer/global_step": self.global_step})

    async def _end_epoch(self, epoch: int) -> None:
        self._control.reset()
        self._control = await self.callback_handler.call_event_async(
            "on_epoch_end", self._create_trainer_state(epoch=epoch), self._control, trainer=self
        )
        ref_callback = self._get_ref_update_callback()
        if self.ref_model is not None and ref_callback is not None and ref_callback.should_update_ref:
            with Timer("update_ref_with_policy", self.all_timings):
                await asyncio.to_thread(self.update_ref_with_policy)

    async def _sync_policy_weights_and_offload_optimizer(
        self, *, sync_phase: Literal["initial", "training_step"]
    ) -> None:
        # Expert-block sync writes into live engine parameters, so the first sync pauses generation too.
        pause = sync_phase == "training_step" or self._expert_block_sync is not None
        if pause:
            await self.inference_engine_client.pause_generation()
        # The shared training path backloads optimizer state before every step when
        # offload_optimizer_during_rollouts is enabled. Offload after each update,
        # including the initial sync, so Megatron gradient buffers are not resized
        # while still resident on the GPU.
        timings = self.all_timings if sync_phase == "training_step" else self.all_startup_timings
        await asyncio.to_thread(self._offload_policy_optimizer, timings, timer_label="offload_policy_optimizer_to_cpu")
        await self.async_sync_policy_weights_to_inference_engines()
        # A hard sync point leaves every policy rank free before the next forward.
        await self._drain_policy_event_loops()
        if pause:
            await self.inference_engine_client.resume_generation()

    async def _run_training(self, training_input: TrainingInputBatch):
        # The initial weight-sync drain can become stale while the rollout
        # buffer fills. Align policy actor loops immediately before every forward.
        await self._drain_policy_event_loops()
        with Timer("fwd_logprobs_values_reward", self.all_timings):
            training_input = await asyncio.to_thread(self.fwd_logprobs_values_reward, training_input)

        if self.cfg.trainer.algorithm.use_kl_in_reward:
            with Timer("apply_reward_kl_penalty", self.all_timings):
                training_input = self.apply_reward_kl_penalty(training_input)

        with Timer("compute_advantages_and_returns", self.all_timings):
            training_input = self.compute_advantages_and_returns(training_input)
            training_input = self.finalize_advantages_for_training(training_input)

        if self.cfg.trainer.dump_data_batch:
            with Timer("dump_data_batch", self.all_timings):
                self.dump_data(training_input, file_name=f"global_step_{self.global_step}_training_input")

        with Timer("train_critic_and_policy", self.all_timings), critical_phase("train_step", self.global_step):
            status = await asyncio.to_thread(self.train_critic_and_policy, training_input)

        return status

    async def async_sync_policy_weights_to_inference_engines(self):
        # Align policy actors before the weight extraction collectives.
        await self._drain_policy_event_loops()
        if self._expert_block_sync is not None:
            timings = await self._expert_block_sync.sync(self.global_step)
            self.all_timings.update(timings.as_metrics())
            logger.info(
                "Expert-block sync: step={} install_seconds={:.3f} policy_seconds={:.3f} receiver_seconds={:.3f} "
                "expert_seconds={:.3f} dense_seconds={:.3f}",
                self.global_step,
                timings.install_seconds,
                timings.policy_seconds,
                timings.receiver_seconds,
                timings.expert_seconds,
                timings.dense_seconds,
            )
            if self.cfg.generator.expert_block_sync.verify:
                self.all_timings.update(await self._expert_block_sync.verify(self.global_step))
            return None
        return await self.policy_model.async_run_method(
            "pass_through", "broadcast_to_inference_engines", self.inference_engine_client
        )

    async def _drain_policy_event_loops(self):
        """Wait for every actor loop to finish pending weight-sync work.

        The next synchronous forward requires all model ranks to enter its
        collectives. An async barrier lets each actor finish its prior coroutine
        before the driver sends that forward.
        """
        refs = self.policy_model.async_run_ray_method("pass_through", "barrier_all")
        await asyncio.gather(*refs)

    def _rollout_stall_timeout(self) -> float:
        """Adaptive deadline between admitted groups.

        An explicit timeout is returned unchanged. Otherwise the deadline is a
        multiple of the recent median step time (at least 10 minutes); before
        step timing exists, it is 30 minutes.
        """
        return AdmissionProgressWatchdog.start(
            now=0.0,
            recent_step_times=self._step_time_history,
            timeout_override=self.group_admission_stall_timeout,
        ).timeout

    def _group_for_teacher_scoring(self, group: RolloutGroup) -> TrajectoryBatch:
        """Apply the learner's row selector without duplicating its metric side effects."""
        if self.trajectory_selector is None:
            return group.trajectory_batch
        row_count = len(group.trajectory_batch["response_ids"])
        return self.trajectory_selector.select(group.trajectory_batch, [group.uid] * row_count).trajectory_batch

    async def _submit_admitted_groups_for_teacher_scoring(self, groups: List[RolloutGroup]) -> None:
        """Enqueue newly admitted groups, letting bounded teacher queues backpressure admission."""
        runtime = self._async_distillation_runtime
        if runtime is None:
            return
        for group in groups:
            self._async_distillation_tickets[group.uid] = await runtime.submit_before_batch_assembly(
                self._group_for_teacher_scoring(group)
            )

    async def _await_admitted_teacher_evidence(
        self,
        groups: List[RolloutGroup],
    ) -> tuple[RoutedScoredDistillationBatch, ...]:
        """Gate learner batch assembly on every admitted group's teacher evidence."""
        missing = [group.uid for group in groups if group.uid not in self._async_distillation_tickets]
        if missing:
            raise RuntimeError(f"admitted groups are missing teacher score tickets: {missing}")
        scored = tuple(
            await asyncio.gather(*(self._async_distillation_tickets[group.uid].result() for group in groups))
        )
        for group, scored_group in zip(groups, scored, strict=True):
            selected_group = self._group_for_teacher_scoring(group)
            trajectory_ids = selected_group.get("trajectory_ids")
            if trajectory_ids is None:
                raise ValueError("teacher scoring requires stable trajectory IDs on admitted groups")
            expected_ids = tuple(trajectory_id.to_string() for trajectory_id in trajectory_ids)
            if scored_group.trajectory_ids != expected_ids:
                raise ValueError(
                    f"teacher evidence row order does not match admitted group {group.uid!r}: "
                    f"expected={expected_ids}, scored={scored_group.trajectory_ids}"
                )
            del self._async_distillation_tickets[group.uid]
        return scored

    def convert_rollout_groups_to_training_input(self, groups: List[RolloutGroup]) -> TrainingInputBatch:
        """Concatenate one batch of admitted groups and convert it to a training batch."""
        max_staleness_steps = self.context.config.max_staleness_steps
        assert len(groups) == self.mini_batch_size, f"Expected {self.mini_batch_size} groups, got {len(groups)}"
        with Timer("assemble_generation_group_mini_batch", self.all_timings):
            uids = [group.uid for group in groups for _ in group.trajectory_batch["response_ids"]]
            stalenesses = [self.global_step - group.policy_step for group in groups]
            record_rollout_staleness(stalenesses, self.global_step)
            assert max(stalenesses) <= max_staleness_steps, (
                f"batch assembly returned staleness {max(stalenesses)} above max {max_staleness_steps}"
            )

            trajectory_batch = concatenate_trajectory_batches(
                [group.trajectory_batch for group in groups],
                require_rollout_logprobs=policy_loss_requires_rollout_logprobs(
                    self.cfg.trainer.algorithm.policy_loss_type
                ),
                tis_lcs_alert_threshold=float(self.cfg.trainer.algorithm.tis_lcs_alert_threshold),
            )
            assert trajectory_batch["rollout_metrics"] is not None, "Rollout metrics should be non-null."
            self.all_metrics.update(trajectory_batch["rollout_metrics"])
            self.all_metrics.update(
                {
                    "async/staleness_mean": sum(stalenesses) / len(stalenesses),
                    "async/staleness_max": max(stalenesses),
                    "async/staleness_min": min(stalenesses),
                    "async/staleness_ratio": sum(1 for s in stalenesses if s > 0) / len(stalenesses),
                }
            )

        with Timer("postprocess_trajectory_batch", self.all_timings):
            trajectory_batch = self.postprocess_trajectory_batch(trajectory_batch, uids)
            trajectory_batch, uids = self.select_trajectories(trajectory_batch, uids)

        logger.debug(f"Example generated: {self.tokenizer.decode(trajectory_batch['response_ids'][0])}")

        with Timer("convert_to_training_input", self.all_timings):
            return self.convert_to_training_input(trajectory_batch, uids)
