"""
Implementation of fully async training in SkyRL.

For details, see https://skyrl.readthedocs.io/en/latest/tutorials/fully_async.html.

High-level notes:
- The global_step in each training loop iteration denotes the "current step being worked on", so
`global_step - 1` is the number of steps the model has finished training.
- We do not do any cross-epoch asynchrony here, so all the control logics like
  generation workers and data buffer are initialized per-epoch. The async dataloader
  and staleness manager are also reset / validated at the end of each epoch.
"""

import asyncio
import os
from marinskyrl.checkpoint_paths import GLOBAL_STEP_PREFIX, LATEST_CHECKPOINT_FILE
from loguru import logger
from skyrl_train.trainer import RayPPOTrainer
from skyrl_train.utils.progress import tqdm
from skyrl_train.utils import Timer, get_system_memory_metrics
from marinskyrl.runtime_options import WeightSyncTransport
from skyrl_train.weight_sync.expert_block.driver import ExpertBlockSync
from skyrl_train.training_batch import TrainingInputBatch
from skyrl_train.trajectory_runners.base import TrajectoryBatch
from skyrl_train.utils.trainer_utils import ResumeMode, build_dataloader
from skyrl_train.utils.logging_utils import log_exception_as_text
from skyrl_train.trajectory_runners.trajectory_processing import concatenate_trajectory_batches
from dataclasses import dataclass
from skyrl_train.utils.data_tracker import DataConsumptionTracker
from skyrl_train.callbacks.builtin import DataTrackingCallback, BufferCheckpointCallback
from torchdata.stateful_dataloader import StatefulDataLoader
from typing import List, Literal, Tuple
from skyrl_train.telemetry import (
    critical_phase,
    record_policy_step,
    record_rollout_staleness,
)
from skyrl_train.timing_observability import publish_step_timings
from skyrl_train.async_rollout_state import GeneratedOutputGroup
from skyrl_train.async_rollout_buffer import AsynchronousRolloutBuffer, _GenerationQueues
from skyrl_train.rollout_worker import (
    AsyncRolloutTaskSource,
    AsyncRolloutWorkerPool,
    bind_rollout_worker,
)
from skyrl_train.io import io
from skyrl_train.dynamic_sampling import (
    DynamicSamplingType,
    GroupSelectionPolicy,
    resolve_dynamic_sampling_criteria,
)
from skyrl_train.distillation_adapters import AsyncRoutedTeacherScoreTicket, RoutedScoredDistillationBatch
from skyrl_train.distillation import DISTILLATION_SCORED_TOKENS_METRIC
from skyrl_train.distillation_runtime import AsyncDistillationRuntime
from skyrl_train.group_admission import (
    AdmissionProgressWatchdog,
    GroupAdmissionPolicy,
)
from skyrl_train.utils.algorithm_registry import policy_loss_requires_rollout_logprobs


@dataclass
class _RolloutStat:
    """
    Global statistics of the trajectories used for staleness control in `_AsyncStalenessManager`.

    Note that these statistics are not per-epoch, but accumulates across all epochs.

    Attributes:
        submitted (int): The number of groups retained in submission-capacity accounting.
            Stale or cancelled attempts decrement it.
        accepted (int): The number of groups finished generation (can be either consumed by,
            or about to be consumed by the training worker). Discarded stale attempts decrement it.
        running (int): The number of groups currently being generated by the generation workers.

    For details, see https://skyrl.readthedocs.io/en/latest/tutorials/fully_async.html#async-staleness-manager
    """

    submitted: int = 0
    accepted: int = 0
    running: int = 0


class _AsyncStalenessManager:
    """
    A controller that manages generation concurrency and on-policy capacity.

    With continuous production, only the number of in-flight groups is bounded;
    the buffer and admission policy decide which completed groups can be trained.
    On-policy mode reserves at most one batch before the next weight update.

    A long-running group can exceed `max_staleness_steps` even when it was
    started within the budget. Admission discards and retries those attempts.

    Positive staleness permits continuous production up to the worker limit;
    zero staleness caps submitted work at one training batch.
    """

    def __init__(
        self,
        max_concurrent_generation_groups: int,
        mini_batch_size: int,
        max_staleness_steps: int,
    ):
        self.max_concurrent_generation_groups = max_concurrent_generation_groups
        self.mini_batch_size = mini_batch_size
        self.max_staleness_steps = max_staleness_steps

        # Control logics.
        self._stat = _RolloutStat()
        self._cond = asyncio.Condition()

        # The current version that is being worked on, i.e. FullyAsyncRayPPOTrainer.global_step.
        # `self._current_global_step - 1` is the number of steps the model has finished training.
        self._current_global_step = 1

    def load_state_from_checkpoint(self, global_step: int) -> None:
        """
        Load the state from a checkpoint.
        """
        self._current_global_step = global_step
        # trainer has already consumed (and hence submitted) this many trajectories.
        self._stat.accepted = (global_step - 1) * self.mini_batch_size
        self._stat.submitted = self._stat.accepted

    async def validate_state_at_epoch_end(self, global_step: int) -> None:
        """
        Check that the current version and accepted rollouts are consistent with the global step.

        Args:
            global_step: The global step we are about to train on (after incrementing).
        """
        async with self._cond:
            assert self._stat.running == 0, "We expect no rollouts are running at end of an epoch."
            assert self._stat.submitted == self._stat.accepted, (
                "We expect all submitted rollouts to be accepted at end of an epoch."
            )
            consumed = (global_step - 1) * self.mini_batch_size
            assert self._stat.accepted == consumed, (
                f"Unexpected number of accepted rollouts. Got {self._stat.accepted} != {consumed}."
            )
            assert self._current_global_step == global_step, (
                f"Unexpected current version. Got {self._current_global_step} != {global_step}."
            )
            assert self._stat.submitted == self._stat.accepted, (
                "We expect all submitted rollouts to be accepted at end of an epoch. "
                f"Got {self._stat.submitted} != {self._stat.accepted}."
            )

    def _compute_capacity_unlocked(self) -> int:
        producer_concurrency_capacity = self.max_concurrent_generation_groups - self._stat.running
        if self.max_staleness_steps > 0:
            return producer_concurrency_capacity
        # NOTE(Charlie): do not need a self._current_global_step + 1 here unlike AReal because our
        # `_current_global_step` is "the version being worked on", not already finished steps.
        consumer_capacity = (self.max_staleness_steps + self._current_global_step) * self.mini_batch_size
        producer_staleness_capacity = consumer_capacity - (self._stat.accepted + self._stat.running)
        return min(producer_concurrency_capacity, producer_staleness_capacity)

    async def acquire_submission_slot(self) -> None:
        """Block until generation capacity is available, then reserve a slot.

        Individual long-running generations can still exceed the aggregate staleness
        budget; those attempts are regenerated before training.
        """
        async with self._cond:
            while self._compute_capacity_unlocked() <= 0:
                await self._cond.wait()
            self._stat.submitted += 1
            self._stat.running += 1

    async def on_rollout_accepted(self) -> None:
        async with self._cond:
            self._stat.accepted += 1
            self._stat.running -= 1
            self._cond.notify_all()

    async def on_rollouts_discarded(self, count: int) -> None:
        """Remove completed rejected attempts from capacity accounting."""
        async with self._cond:
            self._stat.accepted -= count
            self._stat.submitted -= count
            self._cond.notify_all()

    async def cancel_submission_slot(self) -> None:
        """Release a reserved slot without accepting a completed group."""
        async with self._cond:
            self._stat.submitted -= 1
            self._stat.running -= 1
            self._cond.notify_all()

    async def notify_capacity_change(self, new_global_step: int) -> None:
        # Called when current_global_step changes (e.g., after a training step)
        async with self._cond:
            self._current_global_step = int(new_global_step)
            self._cond.notify_all()


class _AsyncDataloader:
    """
    A train dataloader wrapper that accommodates the need of fully async training, including:
    - Thread-safe dataloader iteration with a lock, as there are multiple parallel generation workers polling data.
    - Skip-on-resume: uses DataConsumptionTracker's epoch-scoped UIDs to skip already-consumed data.
    - Finite iteration for ordinary async training and replacement passes for DAPO filter sampling.
    - For finite iteration, set the effective length to a multiple of the mini-batch size because the underlying
      fully async dataloader has batch size 1 and cannot use `drop_last` for the training mini-batch.

    Data consumption tracking (UID recording, epoch transitions, checkpoint persistence)
    is handled by DataConsumptionTracker + DataTrackingCallback, not by this class.
    """

    def __init__(
        self,
        train_dataloader: StatefulDataLoader,
        mini_batch_size: int,
        data_tracker: DataConsumptionTracker,
        dynamic_sampling_type: DynamicSamplingType | None = None,
    ):
        self._train_dataloader = train_dataloader
        self._train_dataloader_initial_state = train_dataloader.state_dict()
        self._sample_with_replacement = dynamic_sampling_type is DynamicSamplingType.FILTER
        self._effective_dataloader_length = (
            len(self._train_dataloader)
            if self._sample_with_replacement
            else len(self._train_dataloader) // mini_batch_size * mini_batch_size
        )
        self._iter = enumerate(self._train_dataloader)
        self._lock: asyncio.Lock = asyncio.Lock()
        self._data_tracker = data_tracker
        self._pending_uids: set[str] = set()
        self._exhausted: bool = False
        self._eligible_rows_returned_in_pass = 0

    def reserve_pending_uids(self, uids: set[str]) -> None:
        """Exclude checkpointed pending work from restarted dataset iteration."""
        self._pending_uids.update(uids)

    def load_state_from_checkpoint(self) -> None:
        """
        Reset dataloader iteration state for resume.

        On resume, the DataConsumptionTracker already has the consumed UIDs loaded.
        We just need to reset the dataloader to the beginning so
        get_next_non_consumed_data() can skip already-consumed items.
        """
        # Reset in case the dataloader loaded the state from the checkpoint, which we do not want.
        self._train_dataloader.load_state_dict(self._train_dataloader_initial_state)
        # Re-create the iterator so get_next_non_consumed_data() starts from
        # the beginning of the dataset (not the exhausted iterator from __init__).
        self._iter = enumerate(self._train_dataloader)
        self._exhausted = False
        self._eligible_rows_returned_in_pass = 0

    async def reset_at_epoch_end(self) -> None:
        """Reset dataloader iterator for the next epoch.

        Note: epoch-scoped UID clearing is handled by DataTrackingCallback.on_epoch_end_async,
        which fires AFTER any checkpoint save — eliminating the race condition where UIDs
        were cleared before the checkpoint captured them.
        """
        async with self._lock:
            self._train_dataloader.load_state_dict(self._train_dataloader_initial_state)  # reset to initial state
            self._iter = enumerate(self._train_dataloader)
            self._pending_uids.clear()
            self._exhausted = False
            self._eligible_rows_returned_in_pass = 0

    async def get_next_non_consumed_data(self):
        """
        Return the next batch of training data.

        If we loaded from a checkpoint, it skips already-consumed data. DAPO filter sampling starts a new source
        pass after exhaustion so rejected prompts can be generated again. Returns None when finite sampling ends or
        when a complete filter pass contains no eligible UID.
        """
        assert self._iter is not None and self._lock is not None, "Dataloader not initialized; call reset() first"
        async with self._lock:
            # Read consumed UIDs after acquiring the iterator lock. Replacement passes can overlap a training step.
            skip_set = self._data_tracker.get_consumed_uids_in_epoch() | self._pending_uids
            while True:
                try:
                    # Keep polling until we get a non-consumed data or the dataloader is exhausted.
                    while True:
                        iter_idx, rand_prompts = next(self._iter)
                        if iter_idx >= self._effective_dataloader_length:
                            raise StopIteration
                        uid = rand_prompts[0]["uid"]
                        if uid not in skip_set:
                            self._eligible_rows_returned_in_pass += 1
                            return rand_prompts
                except StopIteration:
                    if self._sample_with_replacement and self._eligible_rows_returned_in_pass:
                        self._iter = enumerate(self._train_dataloader)
                        self._eligible_rows_returned_in_pass = 0
                        continue
                    self._exhausted = True
                    return None


class FullyAsyncRayPPOTrainer(RayPPOTrainer):
    # Set at startup when generator.weight_sync_transport is expert_block.
    _expert_block_sync: ExpertBlockSync | None = None

    def __init__(self, *args, **kwargs):
        # Extract cfg before base init so we can initialize async-specific knobs used by our overrides.
        cfg = kwargs.get("cfg", args[0] if len(args) > 0 else None)
        assert cfg is not None, "cfg must be provided to FullyAsyncRayPPOTrainer"

        # Initialize async-specific knobs
        self.num_parallel_generation_workers = cfg.trainer.fully_async.num_parallel_generation_workers
        self.mini_batch_size = cfg.trainer.policy_mini_batch_size
        self.max_staleness_steps = cfg.trainer.fully_async.max_staleness_steps
        self.group_admission_stall_timeout = cfg.trainer.algorithm.group_admission.stall_timeout
        self._group_selection_policy = GroupSelectionPolicy.for_fully_async(
            cfg.trainer.algorithm.dynamic_sampling.type,
            criteria=resolve_dynamic_sampling_criteria(
                cfg.trainer.algorithm.dynamic_sampling.informative_on,
                float(cfg.trainer.algorithm.dynamic_sampling.min_reward_std),
            ),
        )
        self._dynamic_sampling_type = self._group_selection_policy.sampling_type
        max_sample_batches = int(cfg.trainer.algorithm.dynamic_sampling.max_sample_batches)
        self._dynamic_sampling_max_sample_batches = max_sample_batches
        self._dynamic_sampling_max_candidate_groups = (
            max_sample_batches * int(cfg.trainer.train_batch_size) if max_sample_batches > 0 else None
        )

        assert (
            # otherwise wasted throughput
            self.mini_batch_size <= self.num_parallel_generation_workers
        ), (
            "Invalid num_parallel_generation_workers, must be >= mini_batch_size. Got: "
            f"{self.mini_batch_size=}, {self.num_parallel_generation_workers=}"
        )
        # Initialize base trainer
        super().__init__(*args, **kwargs)
        self._group_admission_policy = GroupAdmissionPolicy(
            self.group_advantage_invariant,
            max_staleness_steps=self.max_staleness_steps,
            rollout_logprobs_required=policy_loss_requires_rollout_logprobs(
                self.cfg.trainer.algorithm.policy_loss_type
            ),
        )
        # Some async-specific validations
        assert self.cfg.trainer.train_batch_size == self.cfg.trainer.policy_mini_batch_size, (
            "train_batch_size must equal policy_mini_batch_size for fully async training"
        )
        assert not self.cfg.generator.batched, "batched is not supported for fully async training."
        assert self.cfg.generator.async_engine, "async_engine must be True for fully async training."
        # TODO(Charlie): we can support it, just multi-turn partial rollout but synchronous.
        assert not self.colocate_all, "colocate_all is not supported for async training yet."

        # TODO(Charlie): need to assert we are doing TIS and returning logprobs

        # Async-specific states
        self.data_tracker = DataConsumptionTracker(
            mini_batch_size=self.mini_batch_size,
            num_steps_per_epoch=self.num_steps_per_epoch,
        )
        self.async_train_dataloader = _AsyncDataloader(
            self.train_dataloader,
            self.mini_batch_size,
            self.data_tracker,
            self._dynamic_sampling_type,
        )
        # Register the data tracking callback for checkpoint persistence and epoch transitions
        self.callback_handler.add_callback(DataTrackingCallback(self.data_tracker))
        # Register buffer checkpoint callback for saving/restoring generation buffer on resume
        self._buffer_checkpoint_callback = BufferCheckpointCallback()
        self.callback_handler.add_callback(self._buffer_checkpoint_callback)
        self._pending_buffer_restore_path = None
        self._staleness_manager = _AsyncStalenessManager(
            max_concurrent_generation_groups=self.num_parallel_generation_workers,
            mini_batch_size=self.mini_batch_size,
            max_staleness_steps=self.max_staleness_steps,
        )
        # Tracked at instance level so the finally block in train() can cancel
        # them even when an exception skips the per-epoch epilogue.
        self._active_trajectory_tasks: List[asyncio.Task] = []
        self._async_distillation_runtime: AsyncDistillationRuntime | None = None
        self._async_distillation_tickets: dict[str, AsyncRoutedTeacherScoreTicket] = {}

    def configure_async_distillation(self, runtime: AsyncDistillationRuntime) -> None:
        """Install admitted-group teacher scoring before the training loop starts."""
        if self._async_distillation_runtime is not None:
            raise RuntimeError("fully-async distillation runtime is already configured")
        if self._sync_distillation_runtime is not None:
            raise RuntimeError("cannot combine synchronous and fully-async distillation runtimes")
        self._async_distillation_runtime = runtime
        self._domain_balancer = runtime.domain_balancer

    def _configure_training_schedule(self):
        """
        Overrides to build dataloader for fully async training. See `_AsyncDataloader` for more details.
        """
        self.train_dataloader = build_dataloader(self.cfg, self.train_dataset, is_train=True, is_fully_async=True)
        self.num_steps_per_epoch = len(self.train_dataloader) // self.mini_batch_size
        self.total_training_steps = self.num_steps_per_epoch * self.cfg.trainer.epochs
        max_steps = getattr(self.cfg.trainer, "max_steps", None)
        if max_steps is not None and max_steps > 0:
            self.total_training_steps = min(self.total_training_steps, max_steps)
        logger.info(f"Length of train_dataloader: {len(self.train_dataloader)}")
        logger.info(f"Number of steps per epoch: {self.num_steps_per_epoch}")
        logger.info(f"Total training steps: {self.total_training_steps}")

    def _num_steps_per_epoch(self) -> int:
        """Account for fully async mini-batch accumulation."""
        return self.num_steps_per_epoch

    def _cancel_trajectory_tasks(self) -> None:
        """Cancel any active generation tasks left over from an abnormal exit.

        Normally the per-epoch epilogue cancels these, but if an exception
        breaks out of the inner training loop the epilogue is skipped.
        """
        tasks = self._active_trajectory_tasks
        if not tasks:
            return
        n_running = sum(1 for t in tasks if not t.done())
        if n_running:
            logger.warning(f"Cancelling {n_running} orphaned generation tasks from abnormal train loop exit")
            for t in tasks:
                t.cancel()
        self._active_trajectory_tasks = []

    def _restore_buffer_from_checkpoint(self, queues: _GenerationQueues, checkpoint_path: str) -> None:
        """Restore completed, admitted, and retryable rollout work from a checkpoint."""
        buffer_state = BufferCheckpointCallback.load_buffer_state(checkpoint_path)
        completed_count = len(buffer_state.buffer.pending_uids) if buffer_state.buffer is not None else 0
        if buffer_state.buffer is not None:
            queues.rollout_buffer.restore(buffer_state.buffer)
        if len(buffer_state.admitted_groups) > self.mini_batch_size:
            raise ValueError(
                f"Checkpoint contains {len(buffer_state.admitted_groups)} admitted groups, exceeding mini-batch size "
                f"{self.mini_batch_size}"
            )
        self.async_train_dataloader.reserve_pending_uids(buffer_state.pending_uids())
        for prompts in buffer_state.retry_prompts:
            queues.retries.put_nowait(prompts)
        queues.record_admitted(buffer_state.admitted_groups)
        restored_group_count = completed_count + len(buffer_state.admitted_groups)
        self._staleness_manager._stat.accepted += restored_group_count
        self._staleness_manager._stat.submitted += restored_group_count
        logger.info(
            f"Restored {completed_count} completed, "
            f"{len(buffer_state.admitted_groups)} admitted generation groups, and "
            f"{len(buffer_state.retry_prompts)} pending retries "
            "from checkpoint"
        )

    def _latest_checkpoint_step(self) -> int | None:
        marker = os.path.join(self.cfg.trainer.ckpt_path, LATEST_CHECKPOINT_FILE)
        if not io.exists(marker):
            return None
        with io.open_file(marker, "r") as f:
            return int(f.read().strip())

    async def _flush_generation_buffer_on_shutdown(self) -> None:
        """Attach volatile buffer state to the immediately preceding model checkpoint."""
        callback = getattr(self, "_buffer_checkpoint_callback", None)
        if callback is None or not callback.has_bound_queues():
            return
        target_step = self.global_step - 1
        latest_step = await asyncio.to_thread(self._latest_checkpoint_step)
        if latest_step != target_step:
            if callback.has_shutdown_state():
                logger.warning(
                    "Skipping final generation-buffer flush: latest checkpoint step {} is not the immediately "
                    "preceding step {}",
                    latest_step,
                    target_step,
                )
            return
        checkpoint_path = os.path.join(self.cfg.trainer.ckpt_path, f"{GLOBAL_STEP_PREFIX}{target_step}")
        await callback.flush_to_checkpoint(checkpoint_path)

    async def shutdown(self) -> None:
        """Bank the compatible async buffer before releasing trainer resources."""
        if getattr(self, "_shutdown_complete", False):
            return
        try:
            await self._drain_checkpoint_upload()
            await self._flush_generation_buffer_on_shutdown()
        finally:
            if self._expert_block_sync is not None:
                try:
                    await self._expert_block_sync.close()
                except Exception:
                    logger.exception("Closing the expert-block weight sync failed during shutdown")
            async_distillation_runtime = getattr(self, "_async_distillation_runtime", None)
            if async_distillation_runtime is not None:
                await self._close_distillation_runtime(async_distillation_runtime)
            await super().shutdown()

    async def train(self):
        """
        Main fully async training loop for PPO
        """
        self.global_step = 0

        try:
            async_distillation_runtime = getattr(self, "_async_distillation_runtime", None)
            if async_distillation_runtime is not None:
                await async_distillation_runtime.start()
            await self._startup_trajectory_runner()
            await self._train_loop()
        except Exception as e:
            log_exception_as_text(f"Train loop failed at global_step {self.global_step}", e)
            raise
        finally:
            # Cancel any orphaned generation tasks that survived an early exit
            # (the per-epoch epilogue only runs on normal loop completion).
            active_tasks = self._active_trajectory_tasks
            self._cancel_trajectory_tasks()
            if active_tasks:
                await asyncio.gather(*active_tasks, return_exceptions=True)

            try:
                await self.shutdown()
            finally:
                await self._close_rollout_buffer()

    async def _train_loop(self):
        """
        Internal training loop, separated for proper trajectory-runner lifecycle management.
        """
        # Load checkpoint state if resumption is enabled.
        # Data consumption state is loaded via DataTrackingCallback.load_from_checkpoint()
        # into self.data_tracker, which the async dataloader reads for skip-on-resume.
        if self.resume_mode != ResumeMode.NONE:
            with Timer("load_checkpoints", self.all_startup_timings):
                self.global_step, checkpoint_path = self.load_checkpoints()
                logger.info(f"Resumed training from global_step {self.global_step}")

                if self.global_step > 0:
                    # Load data consumption state into the tracker
                    loaded = DataTrackingCallback.load_from_checkpoint(checkpoint_path, self.data_tracker)
                    if not loaded:
                        logger.warning(
                            "No data consumption state found in checkpoint — "
                            "resume may re-train on already-consumed data"
                        )

                    # Store checkpoint path for buffer restore after queue creation
                    self._pending_buffer_restore_path = checkpoint_path

                    # Reset dataloader iteration for skip-on-resume
                    self.async_train_dataloader.load_state_from_checkpoint()
                    self._staleness_manager.load_state_from_checkpoint(
                        self.global_step + 1
                    )  # +1 due to we haven't incremented yet

                    # Soft validation: log mismatch instead of crashing
                    steps_into_epoch = self.global_step % self.num_steps_per_epoch
                    if steps_into_epoch != 0:
                        expected_consumed_in_epoch = self.mini_batch_size * steps_into_epoch
                        actual_consumed_in_epoch = self.data_tracker.consumed_in_epoch_count
                        if actual_consumed_in_epoch != expected_consumed_in_epoch:
                            logger.warning(
                                f"Data consumption count mismatch on resume: "
                                f"expected {expected_consumed_in_epoch}, got {actual_consumed_in_epoch}. "
                                f"This can happen after epoch boundary transitions or error recovery."
                            )

        # Initialize weight sync state
        with Timer("init_weight_sync_state", self.all_startup_timings):
            if self.cfg.generator.weight_sync_transport == WeightSyncTransport.EXPERT_BLOCK:
                self._expert_block_sync = ExpertBlockSync(
                    policy_model=self.policy_model,
                    inference_engine_client=self.inference_engine_client,
                    timeout_seconds=self.cfg.generator.expert_block_sync.timeout_seconds,
                )
                for phase, seconds in (await self._expert_block_sync.prepare()).items():
                    self.all_startup_timings[f"expert_block_sync/{phase}"] = seconds
            else:
                self.init_weight_sync_state()

        # sync weights to inference engines
        with Timer("sync_weights_to_inference_engines", self.all_startup_timings) as weight_update_timer:
            await self._sync_policy_weights_and_offload_optimizer(sync_phase="initial")
        self._log_weight_update_completed(
            reason="initial",
            duration_seconds=weight_update_timer.duration,
        )

        # Synchronize before checking completion so a requested final evaluation uses
        # the checkpoint weights. The loaded global_step is the completed step count;
        # >= treats a resume exactly at max_steps as complete without running gs N+1.
        if self.resume_mode != ResumeMode.NONE and self.global_step >= self.total_training_steps:
            await self._handle_resume_at_max_steps()
            return

        self._log_startup_timings()

        # Create initial trainer state for on_train_begin callback
        start_epoch = self.global_step // self.num_steps_per_epoch
        initial_state = self._create_trainer_state(epoch=start_epoch)

        # Call on_train_begin callbacks (handles eval_before_train via EvaluationCallback)
        self._control.reset()
        self._control = await self.callback_handler.call_event_async(
            "on_train_begin", initial_state, self._control, trainer=self
        )

        # Handle pre-training evaluation if requested by callbacks
        if self._control.should_evaluate and self.eval_dataset is not None:
            with Timer("eval", self.all_timings):
                eval_metrics = await self.eval()
                self._log_metrics_stdout(eval_metrics, step=self.global_step, kind="eval")
                self.tracker.log(eval_metrics, step=self.global_step, commit=self.cfg.trainer.tracker_commit_each_step)
            self._control.should_evaluate = False

        # main training loop
        pbar = tqdm(total=self.total_training_steps, initial=self.global_step, desc="Training Step Progress")
        start_epoch = self.global_step // self.num_steps_per_epoch
        last_completed_step = self.global_step
        self.global_step += 1  # start training at global_step 1
        for epoch in range(start_epoch, self.cfg.trainer.epochs):
            # 0. Per-epoch prologue. Note that we do not do any cross-epoch asynchrony here.

            capacity = 0 if self.max_staleness_steps > 0 else self.mini_batch_size
            rollout_buffer = await self._open_rollout_buffer(capacity, self._staleness_manager)
            generation_queues = _GenerationQueues(
                rollout_buffer=rollout_buffer,
                retries=asyncio.Queue(),
                condition=asyncio.Condition(),
                active_producers=self.num_parallel_generation_workers,
            )

            self._buffer_checkpoint_callback.bind_queues(generation_queues)

            # Restore buffer from checkpoint if resuming
            if self._pending_buffer_restore_path is not None:
                self._restore_buffer_from_checkpoint(
                    generation_queues,
                    self._pending_buffer_restore_path,
                )
                self._pending_buffer_restore_path = None

            # Provide the runner with a live reference to global_step so it can
            # capture the step at first vLLM inference (for accurate staleness tracking).
            self.trajectory_runner.global_step_fn = lambda: self.global_step

            # Maintain self.num_parallel_generation_workers concurrent group-generation workers.
            # Stored on self so the finally block in train() can cancel them on abnormal exit.
            source = AsyncRolloutTaskSource(
                self.async_train_dataloader,
                generation_queues.retries,
                samples_per_prompt=self.cfg.generator.n_samples_per_prompt,
                backend=self.cfg.generator.backend,
                sampling_params=self.cfg.generator.sampling_params,
                environment_class=self.cfg.environment.env_class,
                current_step=lambda: self.global_step,
                stall_timeout=self._generation_stall_timeout,
            )
            worker = bind_rollout_worker(self.trajectory_runner, rollout_buffer, generation_queues.condition)
            self._active_trajectory_tasks = AsyncRolloutWorkerPool(
                worker, source, self.num_parallel_generation_workers, generation_queues.mark_producer_finished
            ).start()
            trajectory_tasks = self._active_trajectory_tasks
            admission_buffer = AsynchronousRolloutBuffer(
                generation_queues,
                mini_batch_size=self.mini_batch_size,
                admission_policy=self._group_admission_policy,
                selection_policy=self._group_selection_policy,
                max_candidate_groups=self._dynamic_sampling_max_candidate_groups,
                max_sample_batches=self._dynamic_sampling_max_sample_batches,
                current_step=lambda: self.global_step,
                consumed_uids=self.data_tracker.get_consumed_uids_in_epoch,
                step_time_history=self._step_time_history,
                stall_timeout=self.group_admission_stall_timeout,
                on_admitted=self._submit_admitted_groups_for_teacher_scoring,
                on_discarded=self._staleness_manager.on_rollouts_discarded,
                retain=worker.retain,
                metrics=lambda: self.all_metrics,
            )

            for _ in range(self.global_step, (1 + epoch) * self.num_steps_per_epoch + 1):
                with Timer("step", self.all_timings) as step_timer:
                    # 1. Discard every completed stale attempt and wait for a full fresh batch.
                    logger.info(
                        "Rollout batch started: step={} mode=fully_async required_groups={}",
                        self.global_step,
                        self.mini_batch_size,
                    )
                    with (
                        Timer("wait_for_generation_buffer", self.all_timings) as rollout_wait_timer,
                        critical_phase("rollout_or_inference_wait", self.global_step),
                    ):
                        cur_generation_group_mini_batch = await admission_buffer.next_batch()

                    scored_distillation = None
                    if self._async_distillation_runtime is not None:
                        with Timer("wait_for_teacher_evidence", self.all_timings):
                            scored_distillation = await self._await_admitted_teacher_evidence(
                                cur_generation_group_mini_batch
                            )

                    # 2. Assemble, post-process, and convert the complete generated mini-batch.
                    training_input = await asyncio.to_thread(
                        self.convert_generation_group_mini_batch_to_training_input,
                        cur_generation_group_mini_batch,
                    )
                    if scored_distillation is not None:
                        self.all_metrics.update(
                            self._async_distillation_runtime.attach_to_training_input(
                                training_input,
                                scored_distillation,
                            )
                        )
                        self.all_metrics.update(
                            {
                                "distillation/teacher_count": float(
                                    len({route.teacher_id for scored in scored_distillation for route in scored.routes})
                                ),
                                DISTILLATION_SCORED_TOKENS_METRIC: float(
                                    sum(scored.distillation.valid_mask.sum().item() for scored in scored_distillation)
                                ),
                            }
                        )
                    response_ids = [
                        response_ids
                        for group in cur_generation_group_mini_batch
                        for response_ids in group.trajectory_batch["response_ids"]
                    ]
                    logger.info(
                        "Rollout batch completed: step={} mode=fully_async groups={} trajectories={} "
                        "response_tokens={} staleness_mean={:.3f} staleness_max={} duration_seconds={:.3f}",
                        self.global_step,
                        len(cur_generation_group_mini_batch),
                        len(response_ids),
                        sum(len(response) for response in response_ids),
                        self.all_metrics["async/staleness_mean"],
                        self.all_metrics["async/staleness_max"],
                        rollout_wait_timer.duration,
                    )

                    # TIS graceful-degrade observability (Fix A): record whether THIS
                    # training batch was missing all rollout logprobs (-> TIS skipped,
                    # standard policy loss used) and a running skipped-fraction. Driver-side
                    # metric only (NOT part of the worker per-key all_reduce(status)), so it
                    # cannot cause the keyset-mismatch NCCL deadlock. skipped_fraction ~1.0
                    # over the run = rollout-logprob capture systematically broken (R3<->logprob
                    # interaction); low = intermittent context-length errors.
                    if self.cfg.trainer.algorithm.use_tis:
                        batch_skipped = float(getattr(self, "_tis_batch_skipped_no_logprobs", 0.0))
                        self._tis_skipped_count = getattr(self, "_tis_skipped_count", 0.0) + batch_skipped
                        self._tis_total_count = getattr(self, "_tis_total_count", 0.0) + 1.0
                        self.all_metrics.update(
                            {
                                "tis/batch_skipped_no_logprobs": batch_skipped,
                                "tis/skipped_fraction": self._tis_skipped_count / self._tis_total_count,
                            }
                        )

                    # 3. Run training and record consumed UIDs in the tracker.
                    with Timer("run_training", self.all_timings):
                        status = await self._run_training(training_input)
                    train_duration = self.all_timings["train_critic_and_policy"]
                    self._log_optimizer_step_completed(
                        epoch=epoch,
                        training_input=training_input,
                        duration_seconds=train_duration,
                    )
                    await self.data_tracker.mark_consumed([g.uid for g in cur_generation_group_mini_batch])
                    generation_queues.mark_admitted_consumed()

                    # 4. After training: sync weights to the inference engines.
                    #    The inference engines are a SHARED HTTP backend that every
                    #    RolloutCoordinator calls, so the STOCK engine-level
                    #    pause/sync/resume below (fast NCCL broadcast with the
                    #    engines briefly quiesced) already propagates fresh weights
                    #    to every coordinator's subsequent requests. We deliberately
                    #    do NOT barrier-pause/drain the RolloutCoordinators at the
                    #    trial level: a coordinator-level drain is unnecessary for
                    #    correctness and defeats async overlap (the hard-drain stalled
                    #    the step boundary indefinitely when long-running trials never
                    #    drained). Rollouts in flight across the weight swap simply
                    #    return as STALE and are bounded by the dispatcher's existing
                    #    max_staleness_steps accounting — exactly like stock
                    #    fully_async, which never drains trial orchestration. This
                    #    block is now byte-identical for fan-out ON and OFF.
                    with Timer("sync_weights", self.all_timings) as weight_update_timer:
                        await self._sync_policy_weights_and_offload_optimizer(sync_phase="training_step")
                    self._log_weight_update_completed(
                        reason="training_step",
                        duration_seconds=weight_update_timer.duration,
                    )

                    # 5. Run callback-requested work before closing the inclusive step timer.
                    logger.info(status)
                    self.all_metrics.update({"trainer/epoch": epoch, "trainer/global_step": self.global_step})
                    step_state = self._create_trainer_state(epoch, active_step_duration=step_timer.elapsed)
                    await self._run_step_end_callbacks(step_state)

                # 6. Log metrics
                if self._control.should_log:
                    log_payload = {
                        **self.all_metrics,
                        **{f"timing/{k}": v for k, v in self.all_timings.items()},
                        **get_system_memory_metrics(),
                    }
                    self._log_metrics_stdout(log_payload, step=self.global_step, kind="train")
                    self.tracker.log(
                        log_payload, step=self.global_step, commit=self.cfg.trainer.tracker_commit_each_step
                    )
                    await self.callback_handler.call_event_async(
                        "on_log", step_state, self._control, logs=log_payload, trainer=self
                    )

                self._log_training_step_completed(
                    epoch=epoch,
                    duration_seconds=step_timer.duration,
                )

                self.all_metrics = {}
                step_duration = self.all_timings.get("step")
                if step_duration is not None:
                    self._step_time_history.append(step_duration)
                publish_step_timings(self.all_timings, self.global_step)
                self.all_timings = {}
                pbar.update(1)

                last_completed_step = self.global_step
                record_policy_step(self.global_step)
                self.global_step += 1
                generation_queues.clear_admitted()

                # 7. Notify generation workers that the capacity has increased, unblocking them.
                await self._staleness_manager.notify_capacity_change(self.global_step)

                # 8. Check for max_steps
                if self.global_step > self.total_training_steps:
                    logger.info(f"Reached max training steps ({self.total_training_steps})")
                    break

                # 9. Check for early stopping
                if self._control.should_training_stop:
                    logger.info("Training stopped early by callback")
                    break

            # 10. Per-epoch epilogue.
            # Call on_epoch_end callbacks
            epoch_state = self._create_trainer_state(epoch=epoch)
            self._control.reset()
            self._control = await self.callback_handler.call_event_async(
                "on_epoch_end", epoch_state, self._control, trainer=self
            )

            # Handle ref model update at epoch end (via RefModelUpdateCallback or direct config)
            ref_callback = self._get_ref_update_callback()
            if self.ref_model is not None and ref_callback is not None and ref_callback.should_update_ref:
                with Timer("update_ref_with_policy", self.all_timings):
                    await asyncio.to_thread(self.update_ref_with_policy)

            # Cancel generation tasks for this epoch
            for t in trajectory_tasks:
                t.cancel()
            try:
                await asyncio.gather(*trajectory_tasks, return_exceptions=True)
            except Exception:
                pass
            self._active_trajectory_tasks = []

            # Per-epoch reset/validation for data loading and staleness management
            assert all(t.done() for t in trajectory_tasks), (
                "Trajectory runner tasks must be done before resetting the dataloader manager and validating the staleness manager."
            )
            # Drain any generation outputs that arrived after the training loop
            # stopped consuming (race between producer enqueue and consumer exit).
            n_drained = len(
                await generation_queues.rollout_buffer.next_batch(generation_queues.rollout_buffer.pending_count())
            )
            assert generation_queues.retries.empty(), (
                f"Epoch ended with {generation_queues.retries.qsize()} stale-group retries still pending"
            )
            if n_drained > 0:
                logger.warning(
                    f"Drained {n_drained} unconsumed generation output(s) at epoch boundary "
                    f"(global_step={self.global_step}). These were generated with stale weights "
                    f"and arrived after the training loop stopped consuming."
                )
                # Reconcile staleness counters for drained items.  Items in the
                # buffer may have been fully accepted (on_rollout_accepted ran)
                # or orphaned (put_nowait succeeded but on_rollout_accepted was
                # interrupted by CancelledError — those are already handled by
                # the CancelledError fix above).  Only undo accepted/submitted
                # for properly-accepted items that were never consumed.
                consumed = (self.global_step - 1) * self.mini_batch_size
                n_accepted_surplus = self._staleness_manager._stat.accepted - consumed
                if n_accepted_surplus > 0:
                    self._staleness_manager._stat.accepted -= n_accepted_surplus
                    self._staleness_manager._stat.submitted -= n_accepted_surplus
            await self.async_train_dataloader.reset_at_epoch_end()
            await self._staleness_manager.validate_state_at_epoch_end(self.global_step)

            if self.global_step > self.total_training_steps:
                break

            if self._control.should_training_stop:
                logger.info("Training stopped early by callback at epoch end")
                break

            # End of an epoch.

        # End of training
        pbar.close()

        await self._finalize_training(
            completed_step=last_completed_step,
            epoch=self.cfg.trainer.epochs - 1,
        )
        logger.info("Training done!")

    async def _sync_policy_weights_and_offload_optimizer(
        self, *, sync_phase: Literal["initial", "training_step"]
    ) -> None:
        # Expert-block sync writes into live engine parameters, so the first sync pauses generation too.
        pause = sync_phase == "training_step" or self._expert_block_sync is not None
        if pause:
            await self.inference_engine_client.pause_generation()
        # The shared training path backloads optimizer state before every step when
        # offload_optimizer_during_rollouts is enabled. Offload after each update,
        # including the initial sync, so Megatron gradient buffers are not resized
        # while still resident on the GPU.
        timings = self.all_timings if sync_phase == "training_step" else self.all_startup_timings
        await asyncio.to_thread(self._offload_policy_optimizer, timings, timer_label="offload_policy_optimizer_to_cpu")
        await self.async_sync_policy_weights_to_inference_engines()
        # A hard sync point leaves every policy rank free before the next forward.
        await self._drain_policy_event_loops()
        if pause:
            await self.inference_engine_client.resume_generation()

    async def _run_training(self, training_input: TrainingInputBatch):
        # TODO(Charlie): share this code with the one-step-off async trainer.
        # The initial weight-sync drain can become stale while the rollout
        # buffer fills. Align policy actor loops immediately before every forward.
        await self._drain_policy_event_loops()
        # inference and calculate values, log probs, rewards, kl divergence
        with Timer("fwd_logprobs_values_reward", self.all_timings):
            training_input = await asyncio.to_thread(self.fwd_logprobs_values_reward, training_input)

        # calculate kl divergence and create experiences
        if self.cfg.trainer.algorithm.use_kl_in_reward:
            with Timer("apply_reward_kl_penalty", self.all_timings):
                training_input = self.apply_reward_kl_penalty(training_input)

        # calculate advantages and returns / along with tensorboard logging
        with Timer("compute_advantages_and_returns", self.all_timings):
            training_input = self.compute_advantages_and_returns(training_input)
            training_input = self.finalize_advantages_for_training(training_input)

        if self.cfg.trainer.dump_data_batch:
            # dump data to file
            with Timer("dump_data_batch", self.all_timings):
                self.dump_data(training_input, file_name=f"global_step_{self.global_step}_training_input")

        # train policy/critic model
        with Timer("train_critic_and_policy", self.all_timings), critical_phase("train_step", self.global_step):
            status = await asyncio.to_thread(self.train_critic_and_policy, training_input)

        return status

    async def async_sync_policy_weights_to_inference_engines(self):
        # Align policy actors before the weight extraction collectives.
        await self._drain_policy_event_loops()
        if self._expert_block_sync is not None:
            timings = await self._expert_block_sync.sync(self.global_step)
            self.all_timings.update(timings.as_metrics())
            logger.info(
                "Expert-block sync: step={} install_seconds={:.3f} policy_seconds={:.3f} receiver_seconds={:.3f} "
                "expert_seconds={:.3f} dense_seconds={:.3f}",
                self.global_step,
                timings.install_seconds,
                timings.policy_seconds,
                timings.receiver_seconds,
                timings.expert_seconds,
                timings.dense_seconds,
            )
            if self.cfg.generator.expert_block_sync.verify:
                self.all_timings.update(await self._expert_block_sync.verify(self.global_step))
            return None
        return await self.policy_model.async_run_method(
            "pass_through", "broadcast_to_inference_engines", self.inference_engine_client
        )

    async def _drain_policy_event_loops(self):
        """Wait for every actor loop to finish pending weight-sync work.

        The next synchronous forward requires all model ranks to enter its
        collectives. An async barrier lets each actor finish its prior coroutine
        before the driver sends that forward.
        """
        refs = self.policy_model.async_run_ray_method("pass_through", "barrier_all")
        await asyncio.gather(*refs)

    def _generation_stall_timeout(self) -> float:
        """Adaptive deadline for receiving new groups during a generation wait.

        An explicit timeout is returned unchanged. Otherwise the deadline is a
        multiple of the recent median step time (at least 10 minutes); before
        step timing exists, it is 30 minutes.
        """
        return AdmissionProgressWatchdog.start(
            now=0.0,
            recent_step_times=self._step_time_history,
            timeout_override=self.group_admission_stall_timeout,
        ).timeout

    def _group_for_teacher_scoring(self, group: GeneratedOutputGroup) -> TrajectoryBatch:
        """Apply the learner's row selector without duplicating its metric side effects."""
        if getattr(self, "trajectory_selector", None) is None:
            return group.trajectory_batch
        row_count = len(group.trajectory_batch["response_ids"])
        return self.trajectory_selector.select(group.trajectory_batch, [group.uid] * row_count).trajectory_batch

    async def _submit_admitted_groups_for_teacher_scoring(self, groups: List[GeneratedOutputGroup]) -> None:
        """Enqueue newly admitted groups, letting bounded teacher queues backpressure admission."""
        runtime = getattr(self, "_async_distillation_runtime", None)
        if runtime is None:
            return
        for group in groups:
            if group.uid in self._async_distillation_tickets:
                continue
            self._async_distillation_tickets[group.uid] = await runtime.submit_before_batch_assembly(
                self._group_for_teacher_scoring(group)
            )

    async def _await_admitted_teacher_evidence(
        self,
        groups: List[GeneratedOutputGroup],
    ) -> tuple[RoutedScoredDistillationBatch, ...]:
        """Gate learner batch assembly on every admitted group's teacher evidence."""
        missing = [group.uid for group in groups if group.uid not in self._async_distillation_tickets]
        if missing:
            raise RuntimeError(f"admitted groups are missing teacher score tickets: {missing}")
        scored = tuple(
            await asyncio.gather(*(self._async_distillation_tickets[group.uid].result() for group in groups))
        )
        for group, scored_group in zip(groups, scored, strict=True):
            selected_group = self._group_for_teacher_scoring(group)
            trajectory_ids = selected_group.get("trajectory_ids")
            if trajectory_ids is None:
                raise ValueError("teacher scoring requires stable trajectory IDs on admitted groups")
            expected_ids = tuple(trajectory_id.to_string() for trajectory_id in trajectory_ids)
            if scored_group.trajectory_ids != expected_ids:
                raise ValueError(
                    f"teacher evidence row order does not match admitted group {group.uid!r}: "
                    f"expected={expected_ids}, scored={scored_group.trajectory_ids}"
                )
            del self._async_distillation_tickets[group.uid]
        return scored

    def convert_generation_group_mini_batch_to_training_input(
        self, cur_generation_group_mini_batch: List[GeneratedOutputGroup]
    ) -> TrainingInputBatch:
        """Convert one complete generated mini-batch to a training batch."""
        assert len(cur_generation_group_mini_batch) == self.mini_batch_size, (
            f"Expected {self.mini_batch_size} generated groups, got {len(cur_generation_group_mini_batch)}"
        )
        with Timer("assemble_generation_group_mini_batch", self.all_timings):
            trajectory_batches = []
            uids = []
            stalenesses = []
            for cur_generated_output_group in cur_generation_group_mini_batch:
                cur_staleness = self.global_step - cur_generated_output_group.earliest_model_step
                stalenesses.append(cur_staleness)
                trajectory_batches.append(cur_generated_output_group.trajectory_batch)
                group_size = len(cur_generated_output_group.trajectory_batch["response_ids"])
                uids.extend([cur_generated_output_group.uid] * group_size)

            record_rollout_staleness(stalenesses, self.global_step)

            assert max(stalenesses) <= self.max_staleness_steps, (
                f"Fresh batch assembly returned staleness {max(stalenesses)} above max {self.max_staleness_steps}"
            )

            trajectory_batch = concatenate_trajectory_batches(
                trajectory_batches,
                require_rollout_logprobs=policy_loss_requires_rollout_logprobs(
                    self.cfg.trainer.algorithm.policy_loss_type
                ),
                tis_lcs_alert_threshold=float(self.cfg.trainer.algorithm.tis_lcs_alert_threshold),
            )
            assert trajectory_batch["rollout_metrics"] is not None, "Rollout metrics should be non-null."
            self.all_metrics.update(trajectory_batch["rollout_metrics"])

            # Log staleness statistics for this step
            self.all_metrics.update(
                {
                    "async/staleness_mean": sum(stalenesses) / len(stalenesses),
                    "async/staleness_max": max(stalenesses),
                    "async/staleness_min": min(stalenesses),
                    "async/staleness_ratio": sum(1 for s in stalenesses if s > 0) / len(stalenesses),
                }
            )

        # Convert rewards to per-token form and compute reward metrics before training conversion
        with Timer("postprocess_trajectory_batch", self.all_timings):
            trajectory_batch = self.postprocess_trajectory_batch(trajectory_batch, uids)
            trajectory_batch, uids = self.select_trajectories(trajectory_batch, uids)

        # print example just for debugging
        vis = self.tokenizer.decode(trajectory_batch["response_ids"][0])
        logger.debug(f"Example generated: {vis}")

        with Timer("convert_to_training_input", self.all_timings):
            return self.convert_to_training_input(trajectory_batch, uids)

    def load_checkpoints(self) -> Tuple[int, str]:
        """
        Load the base checkpoint.

        Data consumption state loading is handled separately via
        DataTrackingCallback.load_from_checkpoint() in _train_loop().

        Returns the global step to resume from and the checkpoint path.
        """
        global_step, checkpoint_path = super().load_checkpoints()
        return global_step, checkpoint_path
