from typing import Literal, Protocol

from torch import Tensor


class MetricReduction(Protocol):
    """Reduce diagnostic tensors at one local or distributed ownership scope."""

    def mean(self, values: Tensor) -> float: ...
    def std(self, values: Tensor) -> float: ...
    def sum(self, values: Tensor) -> Tensor: ...
    def combine(self, values: Tensor, operation: Literal["sum", "max"]) -> Tensor: ...
    def ratios(self, delta: Tensor, *, eps_clip_low: float, eps_clip_high: float) -> dict[str, float]: ...
