zero_optimization:
  stage: 3
  stage3_param_persistence_threshold: "auto"
  offload_param:
    device: cpu
    pin_memory: true
torch_autocast:
  enabled: true
  dtype: bfloat16
gradient_clipping: 1.0
prescale_gradient: false
wall_clock_breakdown: false
