"""Dependency-light constants shared by the phase-divergence controller and worker."""

PROCESS_GROUP_TIMEOUT_SECONDS = 60
WARMUP_MARKER = "MULTI_NODE_COMMUNICATOR_WARMUP_COMPLETED"
READY_MARKER = "MULTI_NODE_FAULT_READY"
ACTIVE_MARKER = "MULTI_NODE_FAULT_ACTIVE"
BLOCKING_WAIT_DISABLED_MARKER = "blocking_wait=None"
UNAFFECTED_EP_COMPLETION_MARKER = "MULTI_NODE_UNAFFECTED_EP_COMPLETED"
UNEXPECTED_COMPLETION_MARKER = "MULTI_NODE_FAULT_UNEXPECTED_COMPLETION"
